apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstdep
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 5
  template:
    metadata:
      name: deppod
      labels:
        app: demo
    spec:
      containers:
      - name: firstone
        image: gcr.io/deft-clarity-328018/myapp:v2
        ports:
        - containerPort: 80
